- config
- grml-debootstrap
- grml-debootstrap.8.txt
The address [`http.debian.net`](http://http.debian.net) is officially replaced by
[`httpredir.debian.org`](http://httpredir.debian.org).
Use the following command to update all places.
git grep -l 'http.debian.net/debian' | xargs sed -i 's,http.debian.net/debian,httpredir.debian.org/debian,g'
> Use official redirector address httpredir.debian.org

- grml-debootstrap
Export $HOSTNAME in $TARGET_HOSTNAME so one is able to do customize things based upon the hostname of the installed machine (eg. to populate /e/n/interfaces by doing a external database lookup).
> Export TARGET_HOSTNAME before running post-scripts

- grml-debootstrap
We are using grml-debootstrap to create various virtual machine in parallel. Our build system started failing after updating to debian stretch, where grml-debootstrap version is 0.78.
When you run multiple grml-debootstrap in parallel, specifying a target in /dev, the bind mount of /dev and /dev/pts makes the successive umount and delete of the temporary mount folder failing.
I think this is caused by how --bind works with recent versions of systemd and udev.
Using proper filesystem definitions in the mount part and removing the bind mount completely solves our problem.
Is this something you think can be pushed upstream or could break compatibility on other systems which are not Debian based?
> Update /dev and /dev/pts mount from --bind to proper fs type

- .travis.yml
- travis/build-vm.sh
- travis/execute.sh
- travis/goss.yaml
We're starting a Docker container with Debian/stretch, installing
the Debian package build result (generated via travis.debian.net)
of grml-debootstrap inside it. Then execute grml-debootstrap,
installing to a VM file. Finally boot the generated VM file via
qemu.
We use stdio of qemu's serial console to check for the boot prompt
of the installed Debian system, using goss for running the actual
checks.
See https://travis-ci.org/mika/grml-debootstrap/jobs/407635286 for the actual test run on TravisCI.
> Initial VM test builds on TravisCI

- grml-debootstrap
kpartx (sometimes) does not cleanup the loop devices when deleting the
partition devmappings. This is a known bug, see [Debian Bug #891077.](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=891077)
This is change is a possible workaround for that issue.
Now aborting a grml-debootstrap is possible without leaving unneded loop
devices behind.
> Improve cleanup of loop devices

- grml-debootstrap
This fix was triggered because running --vmfile to create a virtual
machine image file caused the following error:
| device-mapper: reload ioctl on loop1p1p1 failed: Device or resource busy
| create/reload failed on loop1p1p1
This was caused because kpartx was run twice. The first run was used to test if
the Device-mapper was ready and the second run was actually add the partition
mappings. This used to fail under some circumstances.
> Improve checks to make sure loop and dm-mod module are present

- grml-debootstrap
grml-debootstrap used to happily create a target directory in /dev if
for instance one forgot to partition sda. To avoid such a mistake it
feels better to abort the installation.
Closes: grml/grml-debootstrap#99
> Do not create target directory in /dev

- grml-debootstrap
- grml-debootstrap.8.txt
Predictable Network Interface Names were missing the default
/etc/network/interfaces file when using the --defaultinterfaces option.
Added a Networking-Section in the man page to clarify how the network is
configured in the target system and fixed the documentation for the
options --vmfile and --vm. Both options automatically enable the
--defaultinterface option and not the --nointerfaces option.
Closes: grml/grml-debootstrap#126
> Add DHCP setting for Predictable Network Interface Names

- grml-debootstrap
- grml-debootstrap.8.txt
Use locally available public keys to authorise root login on the target
system.
Similar to ssh-copy-id(1) (without the -i option) it checks if `ssh-add
-L` provides any output, and if so those keys are appended to
`/root/.ssh/authorized_keys`.
Closes: grml/grml-debootstrap#128
> Add option --sshcopyid to authorise root login

- chroot-script
- grml-debootstrap
BOOT_APPEND works only for VMs when being invoked within
grub_install() inside main grml-debootstrap, move its
handling to chroot-script instead.
See https://github.com/grml/grml-debootstrap/issues/106
> Support BOOT_APPEND usage outside of VMs

- chroot-script
For example when partition table is GPT but grub installation
expects a MS-DOS partition table, then grub-install fails
but grml-debootstrap ignored this. Since the system isn't bootable
then this might go unnoticed, so properly fail as soon as grub-install
returns with exit code != 0.
> Properly exit if GRUB installation fails

- chroot-script
Inspired by Marc Haber's bug report #936050 and what Fedora does with their anaconda installer.
> /etc/fstab: provide header comment, pointing to man pages and systemctl daemon-reload

- grml-debootstrap
We retain backwards compatibility, that is: we use keys from the agent
by default. But if unavailable, we tap into the ~/.ssh/authorized_keys
file (or whatever is specified by the $AUTHORIZED_KEYS_SOURCE
environment).
The target SSH directory can be changed with $AUTHORIZED_KEYS_TARGET.
Closes: #151
> add .ssh/authorized_keys support for --sshcopyid

- debian/changelog
- debian/control
- debian/rules
Fixes these lintian issues:
* P: grml-debootstrap source: cute-field debian/control@source Vcs-git vs Vcs-Git
* P: grml-debootstrap source: package-uses-old-debhelper-compat-version 12
* P: grml-debootstrap source: silent-on-rules-requiring-root
* P: grml-debootstrap source: trailing-whitespace debian/changelog (line 1350)
Plus shortens my name.
No binary changes pop up in a diffoscope run.
> Packaging improvements

- grml-debootstrap
> Do not enable escape characters on dumb terminals

- chroot-script
If the configuration includes KEEP_SRC_LIST='no',
then it behaves as if it's set to 'yes', as we were
just checking whether it's set or not.
Closes: grml/grml-debootstrap#160
> Properly handle KEEP_SRC_LIST option when set to 'no'

- chroot-script
- grml-debootstrap
CONFIG_EFI_VARS is no longer available since
https://salsa.debian.org/kernel-team/linux/-/commit/20146398c4599147244ed3ffc54f38d07fb8dea3
(tagged initially as debian/5.10.1-1_exp1 + shipped with kernel package
5.10.1-1~exp1 and newer, incl. 5.10.38-1 as present in current
Debian/unstable). Therefore the kernel module efivars is no longer
available on more recent Debian kernel systems.
Quoting from https://wiki.debian.org/UEFI:
| The older interface was efivars, showing files under
| /sys/firmware/efi/vars, and this is what was used by default in both
| Wheezy and Jessie.
|
| The new interface is efivarfs, which will expose things in a slightly
| different format under /sys/firmware/efi/efivars. This is the new
| preferred way of using UEFI configuration variables, and Debian switched
| to …
> EFI support: check for efivarfs to support Debian kernels >=5.10

- grml-debootstrap
Our partition creation process inside VMs used parted with "mkpart
primary ext4 2M -1", which could end up with unaligned partitions (as
reported in #185):
| (parted) mkpart primary ext4 2M -1
| Warning: The resulting partition is not properly aligned for best performance: 3906s % 4096s != 0s
This depends on the I/O settings of the underlying storage.
The mkpart start at "2M" is interpreted as 2 Megabyte (2000000 bytes or
3906 sectors) from the disk start.  The end "-1" is interpreted as 1
Megabyte (1000000 bytes or 1953 sectors) before the disk end.
On the other hand, "2MiB" is interpreted as 2 Mebibyte (2097152 bytes or
4096 sectors) from the disk start, and "100%" is interpreted as the disk
end.
Quoting from https://www.gnu.org/software/parted/manual/html_node/unit.html:
| Parted will …
> VMs: create partition with alignment starting at 4MiB + ending at 100%

- chroot-script
Also XFS doesn't support the errors=remount-ro option, but instead of disabling the option for file systems that don't support it, let's only enable it for the once that support it (according to linux's source).
Thanks: Chris Hofstaedtler for the bug report
Closes: https://github.com/grml/grml-debootstrap/issues/199
> Use "errors=remount-ro" fstab option only within supported filesystems

- chroot-script
When installing to an XFS root partition, update-initramfs complains:
| update-initramfs: Generating /boot/initrd.img-5.10.0-19-amd64 | W: /sbin/fsck.xfs doesn't exist, can't install to initramfs
Let's make sure to have the according filesystem package available.
FTR, no need for handling ext* + e2fsprogs, as this is available anyways due to `Priority: required`.
Also, the "--filesystem jfs" isn't supported by default (as mkfs.jfs expects user input unless invoked with -q, something we might wanna automate in the future?), but someone can prepare it manually and install it to the mounted file system, so let's also handle this.
Thanks: Chris Hofstaedtler for the bug report
Closes: https://github.com/grml/grml-debootstrap/issues/200
> Ensure to have filesystem tools installed

- grml-debootstrap
As of e2fsprogs v1.43 and Linux kernel v4.4 the ext4 file system supports the new metadata_csum_seed feature (which allows the file system UUID to be modified without needing to update all of the file system metadata). Also see https://bugs.debian.org/1031325
Starting with e2fsprogs v1.47 this new metadata_csum_seed feature gets enabled by default. When installing an older Debian release this might cause problems because it's not fully supported yet, see e.g. the GRUB failure documented as #866603.
To keep the behavior identical to Debian, we do not enable the metadata_csum_seed feature for Debian releases before bookworm.  This is relevant for us, as grml-debootstrap might be running from a more recent Debian release (like a Debian testing/unstable based Grml live system).
We check for …
> Disable ext4 metadata_csum_seed for Debian releases older than bookworm

- chroot-script
We pass the requested --grub … device argument to the GRUB package configuration, like:
```
| # debconf-show grub-pc | grep grub-pc/install_devices: | * grub-pc/install_devices: /dev/sda
```
But the GRUB package tries to use /dev/disk/by-id/... for install_devices setting (since 2010 and Debian/squeeze AFAICS), as can be observed by reconfiguring the GRUB package (which then automatically converts the /dev/sdX to the proper /dev/disk/by-id/... device when being asked in the debconf prompt):
```
| # dpkg-reconfigure grub-pc
| grub-pc: Running grub-install ...
| [...]
| # debconf-show grub-pc | grep grub-pc/install_devices: | * grub-pc/install_devices: /dev/disk/by-id/ata-VBOX_HARDDISK_VBf4f4391c-6316fa69
```
The available_ids() and device_to_id() helper functions are based on code by Colin …
> GRUB: use persistent device names under /dev/disk/by-id/ for install_devices

- docker/Dockerfile
Hi!
The Dockerfile placed at "docker/Dockerfile" contains the best practice violation [DL3059](https://github.com/hadolint/hadolint/wiki/DL3059) detected by the [hadolint](https://github.com/hadolint/hadolint) tool.
The smell DL3059 occurs if there are multiple consecutive RUN instructions. Each RUN will correspond to a layer of the final Docker image, thus is recommended to compact them to reduce the number of layers for the final image.
This pull request proposes a fix for that smell generated by my fixing tool. The patch was manually verified before opening the pull request. To fix this smell, specifically, The consecutive RUN instructions have been chained until a comment or a different instruction appears.
This change is only aimed at fixing that specific smell. If the fix is not …
> Fix for Dockerfile smell DL3059

- grml-debootstrap
- grml-debootstrap.8.txt
This pull request introduces a new option `--vmefi` that will change the VM image to use GPT instead of MBR and adds an ESP partition. Further it will install grub in EFI mode with secure boot support.
Fixes #134
> Add EFI support for VMs

- chroot-script
- grml-debootstrap
* https://github.com/grml/grml-debootstrap/issues/224
> improve error handling

- debian/control
since required for builds with `--vmefi`
fixes https://github.com/grml/grml-debootstrap/issues/225
> add `Depends:` `dosfstools`

- grml-debootstrap
Remove unnecessary use of `eend 0`.
fixes https://github.com/grml/grml-debootstrap/issues/229
> code simplification

- chroot-script
- config
- debian/control
- grml-debootstrap
- grml-debootstrap.8.txt
- packer/Makefile
- packer/debian64_provision.sh
- releasetable.txt
Whoever wants to install such an old release should please use an older grml-debootstrap.
This lets us drop old code, and going forward rely on new features.
Releases before jessie need vsyscall emulation. Jessie itself can only be installed by overriding both debootstrap's and apt's signing key checks. Stretch needs at least `--no-check-gpg` (or maybe another workaround), but for now it is installable.
> Drop support for installing releases before jessie

- grml-debootstrap
Hosts EFI support is unlikely to be related to the VMs EFI support, so this check often only adds noise.
> Skip EFI support check if --vm is given

- chroot-script
- tests/goss.yaml
passwd.postinst enables shadow passwords for the last 16 years. Add a test instead.
> Remove shadowconfig call

- .github/workflows/pr-review.yml
Previously the invocation would silently fail. I am still not sure if it always works,
> ci: fix shellcheck for test scripts

- chroot-script
- grml-debootstrap
- tests/docker-build-vm.sh
* https://github.com/grml/grml-debootstrap/pull/248
* https://github.com/grml/grml-debootstrap/pull/231
Fixes https://github.com/grml/grml-debootstrap/issues/224
> improve error handling 3

- grml-debootstrap
change from EFI to ESP for arm64 builds
Use of ESP is more popular.
* https://en.wikipedia.org/wiki/EFI_system_partition
* https://wiki.archlinux.org/title/EFI_system_partition
* https://www.diskpart.com/articles/efi-system-partition-4348.html
If we'd use the long label it would be "EFI system partition" but since we use the short label it should be ESP.
Why bother? Because then later `PARTLABEL` can be used in `/etc/fstab`.
https://wiki.archlinux.org/title/fstab#GPT_partition_labels
Any label with spaces is more error-prone.
I haven't found any convention for partition labels but consistency makes sense.
> consistently use ESP label for the EFI system partition

- chroot-script
Followup fix for 2708f441697d1b9
Thanks: @adrelanos  for spotting and reporting
Closes: https://github.com/grml/grml-debootstrap/issues/256
Failure with stretch:
```
Processing triggers for initramfs-tools (0.130) ...
update-initramfs: Generating /boot/initrd.img-4.9.0-13-amd64
E: busybox or busybox-static, version 1:1.22.0-17~ or later, is required but not installed
update-initramfs: failed for /boot/initrd.img-4.9.0-13-amd64 with 1.
dpkg: error processing package initramfs-tools (--configure):
subprocess installed post-installation script returned error exit status 1
[...]
invoke-rc.d: policy-rc.d denied execution of try-restart.
Errors were encountered while processing:
initramfs-tools
E: Sub-process /usr/bin/dpkg returned an error code (1)
```
> Install busybox On Debian/stretch as it's required for initramfs

- grml-debootstrap
fixes https://github.com/grml/grml-debootstrap/issues/263
based on https://github.com/grml/grml-debootstrap/pull/262
Not sure if it is acceptable here to have one PR based on top of another.
> consistent umount

- grml-debootstrap
We were using the old-style "RC" error checking. Now that has all been moved to a global error handler, so we need to move log parsing there as well.
Closes: #268
> fix debootstrap error handler

- grml-debootstrap
`try_umount()` replaced all umount calls in PR #264.
Unfortunately, the function is defined too late for a few of functions, especially for cleanup(), which fails with:
```
-> Failed (rc=1)
/sbin/grml-debootstrap: line 260: try_umount: command not found
Unexpected non-zero exit code 127 in /sbin/grml-debootstrap /sbin/grml-debootstrap /sbin/grml-debootstrap /sbin/grml-debootstrap /sbin/grml-debootstrap at line 260 329 1107 1179 0 detected!
last bash command: try_umount 3 "${MNTPOINT}"/boot/efi
-> Failed (rc=1)
/sbin/grml-debootstrap: line 260: try_umount: command not found
```
Moved the `try_umount` above `cleanup()`.
Closes: #271
> Move try_umount above cleanup()

- .github/workflows/pr-review.yml
- .github/workflows/test-build.yml
To manually run a workflow,  the workflow must be configured to run on the workflow_dispatch event.
We want that all our GitHub Actions can be triggered manually.
See:
* https://docs.github.com/en/actions/using-workflows/manually-running-a-workflowk
* https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch
> GitHub Actions: Add workflow_dispatch trigger

- chroot-script
Useful in case it is not cleaned up and later on found on an installed system.
> Tag installed policy-rc.d file

- grml-debootstrap
Invoking `blockdev --rereadpt` straight after creating the file system might fail with:
```
blockdev: ioctl error on BLKRRPART: Device or resource busy
Unexpected non-zero exit code 1 in /sbin/grml-debootstrap /sbin/grml-debootstrap /sbin/grml-debootstrap at line 1376 2132 0 detected!
last bash command: blockdev --rereadpt "$main_device"
```
This is caused by udev kicking in and causing a race condition. Let's invoke udevadm settle (which watches the udev event queue, and exits if all current events are handled), and then retry `blockdev --rereadpt ...` up to 30 times/seconds.
Thanks: Darshaka Pathirana for bug report and initial investigation, and Chris Hofstaedtler for feedback
Closes: https://github.com/grml/grml-debootstrap/issues/273
> mkfs: avoid blockdev failing to re-read partition table

- .github/workflows/test-build.yml
Fixes:
```
| Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/download-artifact@v3, actions/upload-artifact@v3.
| For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
```
Related to grml/grml-debootstrap#278
Thanks: Darshaka Pathirana
> GitHub Actions: raise upload-artifact + download-artifact to v4

- tests/serial-console-connection
Plus Python (formatting) improvements.
> tests/serial-console-connection: add timeout (default to 3min)

- .github/workflows/test-build.yml
- tests/README.md
- tests/build-vm-and-test.sh
- tests/serial-console-connection
- tests/test-vm.sh
@mika wrote most of this, I just rebased it on top of #283 
- Capture VM screenshot when tests fail.
- Add instructions for running the tests locally.
- Ensure curl is installed.
- Update default hostname in helper script.
Debugging aid for #278.
> tests: capture screenshot on failure

- grml-debootstrap
> Disable ext4 feature orphan_file for older releases

- .github/workflows/pr-review.yml
- tests/test-vm.sh
For unknown reasons the pr-review shellcheck-tests workflow started reporting shellcheck errors in non-shell files in `tests/`. Supposedly `check_all_files_with_shebangs: "false"` should prevent this, but alas.
Also fix an actual shellcheck issue.
> shellcheck: restrict shellcheck-tests to tests/*.sh files

- tests/test-vm.sh
From https://salsa.debian.org/ci-team/autopkgtest/-/merge_requests/418
We do not transfer large file, but still.
> tests: set msize=512000 option for 9pfs

- grml-debootstrap
- grml-debootstrap.8.txt
grml-autoconfig dropped this, as it is plainly broken under systemd but nobody has complained.
See https://github.com/grml/grml-autoconfig/pull/17
> Drop support for debian2hd / AUTOINSTALL

- chroot-script
- config
- debian/control
- grml-debootstrap
- grml-debootstrap.8.txt
Noone we know has used in cdebootstrap in ages, and it also is not tested by CI.
Closes #293
> Drop support for cdebootstrap

- grml-debootstrap
When booting Grml from a YUMI device (see https://yumiusb.com/) which was built with Ventoy, then executing `blkid -s TYPE -o value /dev/dm-0p1` might fail, if ventoy is behind the `/dev/dm-0p1` device:
```
root@grml:~# dmsetup ls
ventoy  (253:0)
```
Fixes:
```
++ for i in $AVAILABLE_PARTITIONS
+++ blkid -s TYPE -o value /dev/dm-0p1
++++ error_handler
++++ last_exit_code=2
++++ last_bash_command='blkid -s TYPE -o value "$i" 2> /dev/null' ++++ echo 'Unexpected non-zero exit code 2 in /usr/sbin/grml-debootstrap /usr/sbin/grml-debootstrap /usr/sbin/grml-debootstrap /usr/sbin/grml-debootstrap at line 744 1151 1166 0 detected! last bash command: blkid -s TYPE -o value "$i" 2> /dev/null' ++++ '[' -r /mnt/debootstrap.5465/debootstrap/debootstrap.log ']'
```
Thanks to klatls for the bug report
> interactive mode: ignore failures when identifying file system fails

- chroot-script
- config
- tests/goss.yaml
tzdata 2024b-6 stops creating /etc/timezone, so we should not create it either.
https://salsa.debian.org/glibc-team/tzdata/-/commit/c071fbc167ad306394b576879d515e6ecbe5a734
> Update /etc/timezone only if it exists

- chroot-script
This way a later "apt autoremove" will also remove library/leaf packages installed by the initial bootstrap.
> Mark packages as automatically installed

- chroot-script
- config
- grml-debootstrap
- grml-debootstrap.8.txt
Installing using a loopback-mounted ISO as an unsigned mirror seems not very useful today.
Reference: https://github.com/grml/grml-debootstrap/issues/311
> Drop --iso support

- packages
Should be taken care of by systemd and logind nowadays.
> Stop installing acpi-support-base by default

- grml-debootstrap.8.txt
- releasetable.txt
Nothing seems to use releasetable.txt from any other place, so it can just be in the same file.
Useful if grml.org webpage wants to automatically render the asciidoc content.
> doc: merge releasetable.txt into grml-debootstrap.8.txt

- grml-debootstrap
no longer set redundant environment variables LANG=C and LANGUAGE=C in because already setting LC_ALL=C
https://github.com/grml/grml-debootstrap/issues/310
https://github.com/grml/grml-debootstrap/pull/313
> use `LC_ALL=C` instead of `LANG=C` inside chroot

- .github/workflows/test-build.yml
- grml-debootstrap
- tests/build-vm-and-test.sh
- tests/test-vm.sh
Uses the preview runners, as announced in https://github.blog/changelog/2025-01-16-linux-arm64-hosted-runners-now-available-for-free-in-public-repositories-public-preview/
Fixes one copy of the grub-install cases, broken by PR #316, identified by the new CI runs.
> CI: test on arm hosts

- Makefile
Back then in commit cd8a1e58531fb we introduced the `make shellcheck`. Later on, in commit cb7144264f659 we switched chroot-script from /bin/sh to /bin/bash for error behavior, but didn't adjust the Makefile accordingly.
Thanks: Aaron Rainbolt
Closes: grml/grml-debootstrap#322
> Makefile: mark chroot-script as bash script for shellcheck

- packages
initramfs-tools nowadays defaults to zstd, so install that.
> packages: replace bzip2 with zstd

- packages
libpam-systemd is what enables most of the systemd features we previously installed dbus before. We still get dbus as a dependency of libpam-systemd.
Fixes: 86f83aa4b5047fafa74ef003d2da70bf1eeb50a7
> packages: replace dbus with libpam-systemd

- debian/control
These Depends: entries are not necessary anymore since buster.
Found in https://qa.debian.org/debcheck.php?dist=testing&package=grml-debootstrap
> Cleanup old Depends:

- chroot-script
- config
- grml-debootstrap
- grml-debootstrap.8.txt
Debian stops supporting the "i386" port with trixie, and we have not been testing it for a very long time. Also simplifies some code here.
Closes: grml/grml-debootstrap#321
> Drop support for Debian's "i386" port

- chroot-script
- grml-debootstrap
Fixes https://github.com/grml/grml-debootstrap/issues/297. Quick summary of changes:
* On all EFI-related `grub-install` calls, `--bootloader-id=debian` and `--force-extra-removable` are used. This ensures the bootloader is installed both to the distro-specific path (`/boot/efi/EFI/debian`) and to the removable media path. `--removable` is removed from these calls as it is no longer needed and in fact prevents the normal bootloader location from being installed to. Its job is done by `--force-extra-removable` now.
* If `--vmefi` is enabled, `grub-pc-bin` is installed rather than `grub-pc`, allowing the BIOS bootloader to be *installed* but not allowing it to be automatically updated. This is to allow installing `grub-efi-ARCH`, which allows automatically updating the EFI bootloader. …
> Make bootloader updates on UEFI-based systems work

- chroot-script
- grml-debootstrap
Previously, we had two separate implementations of GRUB installation code, one that worked for physical disks and one that worked for virtual disks. The physical disk code works for virtual disks with some minor changes, so make those changes and discard the virtual disk bootloader installer.
Fixes https://github.com/grml/grml-debootstrap/issues/320
Needs intensive testing before merging.
> Deduplicate GRUB installation code

- grml-debootstrap
Absence of an EFI runtime does not prevent loading efivarfs since commit
torvalds/linux@301de9a2055357375a4e1053d9df0f8f3467ff00 which landed in Linux v6.3.
Thus our check code cannot work anymore, and the message is at best misleading.
> efi_support: drop BIOS-mode info

- grml-debootstrap
When invoking grml-debootstrap with `--grub /dev/`, it fails with:
```
| Installing for i386-pc platform.
| grub-install: error: cannot read `/dev': Is a directory. | Error: failed to execute 'grub-install --no-floppy --target=i386-pc /dev/'.
```
This is caused by our own invocation of `grub-install --no-floppy --target=i386-pc "${device}`, while we're also setting GRUB's debconf to `grub-cloud-amd64/install_devices: /dev/`.
Furthermore, when invoking grml-debootstrap with `--grub /dev/fail`, it fails hard - but non-obvious - within invocation of efibootmgr:
```
| Invoking efibootmgr
| BootCurrent: 0003
| Timeout: 1 seconds
| [...]
| MirrorStatus: Platform does not support address range mirror | DesiredMirroredPercentageAbove4G: 0.00
| DesiredMirrorMemoryBelow4GB: false
| Unexpected …
```
> Verify that GRUB configuration points to valid block device

- grml-debootstrap
Pretty much what the title says, not very complicated. Worthy of note, this only affects VMs using GPT partitioning (since that's mandatory for partition type UUIDs), which currently means non-EFI systems won't get this fanciness due to the fact that grml-debootstrap doesn't support making BIOS-only GPT-formatted VMs.
Tested both amd64 and arm64 VM builds on a Trixie machine, the root partition type UUID is set properly in both instances.
> Set root partition type UUIDs for VM images according to the Discoverable Partition Specification

- chroot-script
Fixes part of https://github.com/grml/grml-debootstrap/issues/339.
> Don't set bogus debconf variable on grub-cloud packages

- .github/workflows/test-build.yml
- Makefile
- Vagrantfile
- chroot-script
- config
- docker/test_dirinstall.bats
- docker/test_vminstall.bats
- grml-debootstrap
- grml-debootstrap.8.txt
- packer/Makefile
- packer/debian64_provision.sh
The buster repository was moved to archive.debian.org, see https://lists.debian.org/debian-devel-announce/2025/06/msg00001.html We decided to no longer invest any further time into buster.
Relevant changes:
* Drop all buster related code/config/docs
* Replace buster with trixie, whenever applicable
* prompt_for_release(): do not hardcode height of dialog, but instead use "0" to use dialog's autodetection instead.
* config: update release information to match reality
* grml-debootstrap.8.txt: update documentation accordingly
* Makefile + packer/Makefile: the compile target is gone since commit 4d625ea05ba167d60766f86f2ff2edad2cfd561a
Closes: https://github.com/grml/grml-debootstrap/issues/349
> Drop support for Debian v10 / buster
